export const projectsdata = [
  {
    id: 1,
    title: 'E-Commerce Shoe Store',
    description:
      'A full-featured online shoe store with product management, cart, checkout, and admin analytics dashboard.',
    technologies: [
      'Next.js',
      'Node.js',
      'MongoDB',
      'Tailwind CSS',
      'Cloudinary',
    ],
    category: 'Web App',
    image: 'https://picsum.photos/seed/project1/800/600',
    github: 'https://github.com/rohitpatel/shoe-store',
    liveDemo: 'https://shoestore.example.com',
    client: 'Urban Kicks',
    duration: '2 months',
    status: 'Completed',
    createdAt: '2024-04-15',
  },
  {
    id: 2,
    title: 'Gym Management System',
    description:
      'A fullstack gym membership system with trainer scheduling, payments, and role-based admin access.',
    technologies: ['React', 'Express.js', 'MySQL', 'JWT', 'Stripe'],
    category: 'SaaS',
    image: 'https://picsum.photos/seed/project2/800/600',
    github: 'https://github.com/rohitpatel/gym-system',
    liveDemo: 'https://gympro.example.com',
    client: 'FitZone India',
    duration: '3 months',
    status: 'Completed',
    createdAt: '2024-05-01',
  },
  {
    id: 3,
    title: 'AI Video Creator',
    description:
      'A Next.js-based AI platform where users can generate short videos using text prompts with real-time preview and download.',
    technologies: [
      'Next.js',
      'OpenAI API',
      'Tailwind CSS',
      'Cloudinary',
      'Framer Motion',
    ],
    category: 'AI Tool',
    image: 'https://picsum.photos/seed/project3/800/600',
    github: 'https://github.com/rohitpatel/ai-video-creator',
    liveDemo: 'https://aivideo.example.com',
    client: 'Personal Project',
    duration: '1 month',
    status: 'In Progress',
    createdAt: '2025-01-05',
  },
  {
    id: 4,
    title: 'Portfolio Website',
    description:
      'Personal portfolio website to showcase my projects, skills, and contact information with smooth animations and modern UI.',
    technologies: ['Next.js', 'Framer Motion', 'Tailwind CSS'],
    category: 'Portfolio',
    image: 'https://picsum.photos/seed/project4/800/600',
    github: 'https://github.com/rohitpatel/portfolio',
    liveDemo: 'https://rohitpatel.dev',
    client: 'Self',
    duration: '2 weeks',
    status: 'Completed',
    createdAt: '2024-03-12',
  },
  {
    id: 5,
    title: 'Travel Booking App',
    description:
      'End-to-end travel booking platform with destinations, hotel listings, flight integration, and booking management.',
    technologies: ['React', 'Node.js', 'MongoDB', 'JWT', 'Stripe'],
    category: 'Web App',
    image: 'https://picsum.photos/seed/project5/800/600',
    github: 'https://github.com/rohitpatel/travel-booking',
    liveDemo: 'https://journeygo.example.com',
    client: 'JourneyGo Pvt Ltd',
    duration: '4 months',
    status: 'Completed',
    createdAt: '2024-07-20',
  },
  {
    id: 6,
    title: 'Restaurant Reservation System',
    description:
      'A restaurant booking system that allows users to reserve tables, manage menus, and handle online orders.',
    technologies: ['Vue.js', 'Firebase', 'Tailwind CSS'],
    category: 'Web App',
    image: 'https://picsum.photos/seed/project6/800/600',
    github: 'https://github.com/rohitpatel/restaurant-reservation',
    liveDemo: 'https://bookmydine.example.com',
    client: 'FoodCrafts',
    duration: '6 weeks',
    status: 'Completed',
    createdAt: '2023-11-05',
  },
  {
    id: 7,
    title: 'Crypto Dashboard',
    description:
      'A live cryptocurrency price dashboard with chart visualizations, portfolio tracker, and dark/light mode toggle.',
    technologies: ['Next.js', 'Chart.js', 'Tailwind CSS', 'CoinGecko API'],
    category: 'Finance',
    image: 'https://picsum.photos/seed/project7/800/600',
    github: 'https://github.com/rohitpatel/crypto-dashboard',
    liveDemo: 'https://cryptohub.example.com',
    client: 'Self',
    duration: '1 month',
    status: 'Completed',
    createdAt: '2024-08-12',
  },
  {
    id: 8,
    title: 'Real Estate Listing Platform',
    description:
      'Full-stack property listing platform where users can post, search, and manage real estate listings with images.',
    technologies: ['Next.js', 'Node.js', 'MongoDB', 'Cloudinary'],
    category: 'Web App',
    image: 'https://picsum.photos/seed/project8/800/600',
    github: 'https://github.com/rohitpatel/real-estate-platform',
    liveDemo: 'https://propertyhub.example.com',
    client: 'PropertyHub',
    duration: '3 months',
    status: 'Completed',
    createdAt: '2024-02-01',
  },
  {
    id: 9,
    title: 'Chat Application',
    description:
      'Real-time chat app with user authentication, typing indicators, file sharing, and dark/light theme.',
    technologies: ['React', 'Socket.io', 'Node.js', 'MongoDB'],
    category: 'Communication',
    image: 'https://picsum.photos/seed/project9/800/600',
    github: 'https://github.com/rohitpatel/chat-app',
    liveDemo: 'https://chatterverse.example.com',
    client: 'Team Chatly',
    duration: '2 months',
    status: 'Completed',
    createdAt: '2023-10-20',
  },
  {
    id: 10,
    title: 'Learning Management System (LMS)',
    description:
      'Platform for managing online courses, student progress, and instructor dashboards with payment integration.',
    technologies: ['React', 'Express.js', 'MySQL', 'JWT', 'Stripe'],
    category: 'Education',
    image: 'https://picsum.photos/seed/project10/800/600',
    github: 'https://github.com/rohitpatel/lms-platform',
    liveDemo: 'https://learnpro.example.com',
    client: 'EduNext',
    duration: '5 months',
    status: 'Completed',
    createdAt: '2024-06-01',
  },
  {
    id: 11,
    title: 'Personal Finance Tracker',
    description:
      'A finance app that helps users track their expenses, visualize budgets, and set savings goals.',
    technologies: ['Next.js', 'Chart.js', 'MongoDB', 'Tailwind CSS'],
    category: 'Finance',
    image: 'https://picsum.photos/seed/project11/800/600',
    github: 'https://github.com/rohitpatel/finance-tracker',
    liveDemo: 'https://finwise.example.com',
    client: 'Self',
    duration: '6 weeks',
    status: 'Completed',
    createdAt: '2024-09-22',
  },
  {
    id: 12,
    title: 'Event Management Portal',
    description:
      'A platform to organize and promote events, sell tickets, and manage attendee registration online.',
    technologies: ['React', 'Firebase', 'Tailwind CSS'],
    category: 'Event',
    image: 'https://picsum.photos/seed/project12/800/600',
    github: 'https://github.com/rohitpatel/event-portal',
    liveDemo: 'https://eventify.example.com',
    client: 'Eventify Pvt Ltd',
    duration: '3 months',
    status: 'Completed',
    createdAt: '2023-12-05',
  },
  {
    id: 13,
    title: 'Blog CMS Platform',
    description:
      'A custom CMS for writers with markdown editor, category filters, and admin content management dashboard.',
    technologies: ['Next.js', 'MongoDB', 'Tailwind CSS', 'JWT'],
    category: 'CMS',
    image: 'https://picsum.photos/seed/project13/800/600',
    github: 'https://github.com/rohitpatel/blog-cms',
    liveDemo: 'https://writeit.example.com',
    client: 'Personal Project',
    duration: '2 months',
    status: 'Completed',
    createdAt: '2024-10-10',
  },
  {
    id: 14,
    title: 'AI Resume Builder',
    description:
      'Web app that uses AI to generate personalized resumes and portfolio suggestions based on user input.',
    technologies: ['Next.js', 'OpenAI API', 'Tailwind CSS', 'Framer Motion'],
    category: 'AI Tool',
    image: 'https://picsum.photos/seed/project14/800/600',
    github: 'https://github.com/rohitpatel/ai-resume-builder',
    liveDemo: 'https://airesume.example.com',
    client: 'Self',
    duration: '1 month',
    status: 'Completed',
    createdAt: '2025-01-15',
  },
  {
    id: 15,
    title: 'Hotel Booking System',
    description:
      'A hotel booking web app with room availability, reservation management, and admin analytics.',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'JWT'],
    category: 'Web App',
    image: 'https://picsum.photos/seed/project15/800/600',
    github: 'https://github.com/rohitpatel/hotel-booking',
    liveDemo: 'https://staywise.example.com',
    client: 'StayWise Group',
    duration: '3 months',
    status: 'Completed',
    createdAt: '2024-03-18',
  },
  {
    id: 16,
    title: 'Online Food Delivery App',
    description:
      'Food ordering platform where users can browse restaurants, track orders, and make secure payments.',
    technologies: ['React', 'Redux', 'Node.js', 'MongoDB'],
    category: 'Delivery',
    image: 'https://picsum.photos/seed/project16/800/600',
    github: 'https://github.com/rohitpatel/food-delivery',
    liveDemo: 'https://yummify.example.com',
    client: 'Yummify Pvt Ltd',
    duration: '4 months',
    status: 'Completed',
    createdAt: '2024-05-25',
  },
  {
    id: 17,
    title: 'Freelance Management Dashboard',
    description:
      'Dashboard for freelancers to manage clients, payments, and project deadlines with invoice automation.',
    technologies: ['Next.js', 'Supabase', 'Tailwind CSS'],
    category: 'Dashboard',
    image: 'https://picsum.photos/seed/project17/800/600',
    github: 'https://github.com/rohitpatel/freelance-dashboard',
    liveDemo: 'https://freelancely.example.com',
    client: 'Freelancely',
    duration: '2 months',
    status: 'Completed',
    createdAt: '2024-11-15',
  },
  {
    id: 18,
    title: 'Inventory Management System',
    description:
      'A robust inventory app for small businesses with real-time stock tracking, reports, and alerts.',
    technologies: ['Node.js', 'Express.js', 'MySQL', 'React'],
    category: 'Business',
    image: 'https://picsum.photos/seed/project18/800/600',
    github: 'https://github.com/rohitpatel/inventory-system',
    liveDemo: 'https://stocksmart.example.com',
    client: 'TechServe Ltd',
    duration: '3 months',
    status: 'Completed',
    createdAt: '2024-04-02',
  },
  {
    id: 19,
    title: 'Weather Forecast App',
    description:
      'Simple weather web app using OpenWeather API with location detection and animated UI.',
    technologies: ['React', 'Tailwind CSS', 'OpenWeather API'],
    category: 'Utility',
    image: 'https://picsum.photos/seed/project19/800/600',
    github: 'https://github.com/rohitpatel/weather-app',
    liveDemo: 'https://weathrify.example.com',
    client: 'Self',
    duration: '2 weeks',
    status: 'Completed',
    createdAt: '2024-09-02',
  },
  {
    id: 20,
    title: 'Music Streaming Platform',
    description:
      'Spotify-like web app to stream songs, create playlists, and follow artists using modern tech stack.',
    technologies: ['Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    category: 'Entertainment',
    image: 'https://picsum.photos/seed/project20/800/600',
    github: 'https://github.com/rohitpatel/music-stream',
    liveDemo: 'https://soundwave.example.com',
    client: 'SoundWave Media',
    duration: '5 months',
    status: 'Completed',
    createdAt: '2024-08-05',
  },
]
